# Generated by Django 3.2.9 on 2021-12-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20211217_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribeduserscategory',
            old_name='user',
            new_name='subscribed_users',
        ),
    ]
